---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Christine Wieder"
title: "#Readwomen2014 -- Eine Online-Aktion mit nachhaltigen Auswirkungen auf unser Leseverhalten und den Literaturbetrieb?"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100215896"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---
