
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>Communitybuilding über Discord – der DACH-Bibliothekswesen-Server - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="Communitybuilding über Discord – der DACH-Bibliothekswesen-Server" />
    
    
    
    <meta property="dc:creator" content="Victoria Geske" />
    
    <meta property="dc:creator" content="Yannick Paulsen" />
    
    <meta property="dc:creator" content="Heidrun Wiesenmüller" />
    
    <meta property="dc:creator" content="Daniel Brenn" />
    
    <meta property="dc:creator" content="Beat Mattmann" />
    
    
    
    <meta property="dc:date" content="2021" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe39/discord/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content="Discord ist ein Dienst, der ursprünglich aus der Gaming-Szene kommt, mit dem man als Gruppe online miteinander kommunizieren kann. Selbst erstellte Server können gestaltet werden, wie es zum jeweiligen Freundeskreis oder der Community passt, und umfassen sowohl schriftlichen als auch audiovisuellen Austausch. Den hier thematisierten Server für Bibliotheksmenschen gibt es seit Februar 2021. Das Interview fand am 22.06.21 über Videochat statt. Zu diesem Zeitpunkt waren knapp 1200 Nutzer*innen registriert."/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="39" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2021" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe39/discord/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe41/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">Autor*innen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Author guidelines</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
    <a class="sidebar-nav-item" href="https://www.zotero.org/groups/4620604/">Zotero DLDL</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <a href="mailto:redaktion@libreas.eu"><i class="fa fa-envelope"></i></a>
        <a href="https://github.com/libreas"><i class="fa fa-github-square"></i></a>
        <a href="https://www.instagram.com/libreas.libraryideas/"><i class="fa fa-instagram"></i></a>
        <a href="https://twitter.com/libreas"><i class="fa fa-twitter"></i></a>
        <a href="https://github.com/libreas.atom"><i class="fa fa-rss"></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe39/inhalt/">LIBREAS. Library Ideas # 39</a></strong> <br><br>
</div>




    
        
    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe39/discord/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="https://doi.org/10.18452/23451">Download PDF</a></small>
        </div>
    
    
    <div align="right">
        <small><a itemprop="sameAs" href="https://doi.org/10.18452/23451">doi:10.18452/23451</a> (edoc HU Berlin)</small>
        </div>
        

        
        <h1 itemprop="name" class="title">Communitybuilding über Discord – der DACH-Bibliothekswesen-Server</h1>
        
        

        <div class="titelei">
        
        <i itemprop="author">Victoria Geske, Yannick Paulsen, Heidrun Wiesenmüller, Daniel Brenn, Beat Mattmann</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Victoria Geske</i> 
            
            
              
            <i itemprop="author">Yannick Paulsen</i>
            
            
              
            <i itemprop="author">Heidrun Wiesenmüller</i>
            
            
              
            <i itemprop="author">Daniel Brenn</i>
            
            
               
            </i><i itemprop="author">Beat Mattmann</i>
            
            
            
        </div>
 -->



        

        <p><small itemprop="description">Discord ist ein Dienst, der ursprünglich aus der Gaming-Szene kommt, mit dem man als Gruppe online miteinander kommunizieren kann. Selbst erstellte Server können gestaltet werden, wie es zum jeweiligen Freundeskreis oder der Community passt, und umfassen sowohl schriftlichen als auch audiovisuellen Austausch. Den hier thematisierten Server für Bibliotheksmenschen gibt es seit Februar 2021. Das Interview fand am 22.06.21 über Videochat statt. Zu diesem Zeitpunkt waren knapp 1200 Nutzer*innen registriert.</small></p>

        

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Victoria Geske,
            
            
            
            Yannick Paulsen,
            
            
            
            Heidrun Wiesenmüller,
            
            
            
            Daniel Brenn,
            
            
            
            Beat Mattmann,
            
            
             
            "Communitybuilding über Discord – der DACH-Bibliothekswesen-Server".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 39 (<span itemprop="datePublished">2021</span>). <a itemprop="url" href="https://libreas.eu/ausgabe39/discord/meta.yaml">https://libreas.eu/ausgabe39/discord/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2022-12-06</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
