
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>Kamptaler Sakrallandschaften im Wikiversum - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="Kamptaler Sakrallandschaften im Wikiversum" />
    
    
    
    <meta property="dc:creator" content="Christian Erlinger" />
    
    <meta property="dc:creator" content="Jens Bemme" />
    
    
    
    <meta property="dc:date" content="2023" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe44/erlinger-bemme/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content="Die Autoren skizzieren, dass insbesondere lokales und regionales Wissen mit Wikis entsteht und dauerhaft bleibt – als Regionalia in globalen offenen Linkzusammenhängen. &lt;q&gt;Grass Root Open Access&lt;/q&gt; bedeutet nicht nur, Publikationen auf selbst gezimmerte Art und Weise frei und unter offener Lizenz zu publizieren (&lt;q&gt;I have published my pdf under a cc license on my personal website&lt;/q&gt;). &lt;q&gt;Grass Root Open Science&lt;/q&gt; bedeutet auch, den Inhalt, die Daten und Bilder &amp;mdash; das Wissen einer publizistischen Arbeit an sich frei, offen und reproduzierbar zu veröffentlichen. Am Beispiel der &lt;q&gt;Wikifizierung&lt;/q&gt; einer gedruckten, heimatkundlichen Buchpublikation wird gezeigt, wie mit Graswurzelstrategien im Wikiversums Open Science entsteht.&lt;br&gt; Wir skizzieren einen solchen Prozess als &#39;linked open&#39;: Methoden und Effekte regionaler Datenpflege als demokratisierende Praxis mittels Citizen Science, mit Blick auf Technologien und Gemeinschaften. Potentiell beeinflussen wir mit offenen, wiki-basierten und damit dezentralen Wissenssystemen die Kalkulation und Rentabilität öffentlicher und quasi-öffentlicher Investitionen in Bildungsressourcen, Informationsinfrastrukturen, Forschung und Entwicklung."/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="44" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2023" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe44/erlinger-bemme/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe44/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">Autor*innen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Author guidelines</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
    <a class="sidebar-nav-item" href="/dldl.html">DLDL</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <a href="mailto:redaktion@libreas.eu"><i class="fa fa-envelope"></i></a>
        <a href="https://github.com/libreas"><i class="fa fa-github-square"></i></a>
        <a href="https://www.instagram.com/libreas.libraryideas/"><i class="fa fa-instagram"></i></a>
        <a href="https://twitter.com/libreas"><i class="fa fa-twitter"></i></a>
        <a href="https://edoc.hu-berlin.de/feed/atom_1.0/18452/149"><i class="fa fa-rss"></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe44/inhalt/">LIBREAS. Library Ideas # 44</a></strong> <br><br>
</div>





    
        
    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe44/erlinger-bemme/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="https://doi.org/10.18452/28263">Download PDF</a></small>
        </div>
    
    
    <div align="right">
        <small><a itemprop="sameAs" href="https://doi.org/10.18452/28263">doi:10.18452/28263</a> (edoc HU Berlin)</small>
        </div>
        

        
        <h1 itemprop="name" class="title">Kamptaler Sakrallandschaften im Wikiversum</h1>
        
        <h2><small>Edits mit Versionsgeschichte: Elementarteilchen offener Wissensproduktion am Beispiel eines Citizen Science-Projektes</small></h2>
        
        

        <div class="titelei">
        
        <i itemprop="author">Christian Erlinger, Jens Bemme</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Christian Erlinger</i> 
            
            
               
            </i><i itemprop="author">Jens Bemme</i>
            
            
            
        </div>
 -->



        

        <p><small itemprop="description">Die Autoren skizzieren, dass insbesondere lokales und regionales Wissen mit Wikis entsteht und dauerhaft bleibt – als Regionalia in globalen offenen Linkzusammenhängen. <q>Grass Root Open Access</q> bedeutet nicht nur, Publikationen auf selbst gezimmerte Art und Weise frei und unter offener Lizenz zu publizieren (<q>I have published my pdf under a cc license on my personal website</q>). <q>Grass Root Open Science</q> bedeutet auch, den Inhalt, die Daten und Bilder &mdash; das Wissen einer publizistischen Arbeit an sich frei, offen und reproduzierbar zu veröffentlichen. Am Beispiel der <q>Wikifizierung</q> einer gedruckten, heimatkundlichen Buchpublikation wird gezeigt, wie mit Graswurzelstrategien im Wikiversums Open Science entsteht.<br> Wir skizzieren einen solchen Prozess als 'linked open': Methoden und Effekte regionaler Datenpflege als demokratisierende Praxis mittels Citizen Science, mit Blick auf Technologien und Gemeinschaften. Potentiell beeinflussen wir mit offenen, wiki-basierten und damit dezentralen Wissenssystemen die Kalkulation und Rentabilität öffentlicher und quasi-öffentlicher Investitionen in Bildungsressourcen, Informationsinfrastrukturen, Forschung und Entwicklung.</small></p>

        

        

        <br>

        <p><small itemprop="description">The authors outline that local and regional knowledge in particular is created with wikis and remains permanent. 'Grass Root Open Access' does not only mean publishing freely and under an open licence in a self-made way ('I have published my pdf under a cc license on my personal website'). 'Grass Root Open Science' means publishing the content, data and images - the knowledge of the scientific work itself - freely, openly and reproducibly. Using the example of the 'wikification' of a printed local history book publication, we show how grass root strategies in the Wikiverse can be used to create Open Science. We outline such a process 'linked open': Methods and effects of regional data creation as a democratizing practice with open wiki-based and thus decentralized knowledge systems, we potentially influence the calculation and profitability of public and quasi-public investments in educational resources, in information infrastructures, in research and development.<br>We outline such a process 'linked open': Methods and effects of regional data creation as a democratizing practice with open wiki-based and thus decentralized knowledge systems, we potentially influence the calculation and profitability of public and quasi-public investments in educational resources, in information infrastructures, in research and development.</small></p>

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Christian Erlinger,
            
            
            
            Jens Bemme,
            
            
            
            "Kamptaler Sakrallandschaften im Wikiversum. Edits mit Versionsgeschichte: Elementarteilchen offener Wissensproduktion am Beispiel eines Citizen Science-Projektes".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 44 (<span itemprop="datePublished">2023</span>). <a itemprop="url" href="https://libreas.eu/ausgabe44/erlinger-bemme/meta.yaml">https://libreas.eu/ausgabe44/erlinger-bemme/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2024-07-12</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
