
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>Buch, Karow. Ein Ortstermin in zwei Berliner öffentlichen Bibliotheken - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="Buch, Karow. Ein Ortstermin in zwei Berliner öffentlichen Bibliotheken" />
    
    
    
    <meta property="dc:creator" content="Ben Kaden" />
    
    
    
    <meta property="dc:date" content="2017" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe31/pankow/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content=""/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="31" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2017" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe31/pankow/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe45/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">Autor*innen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Author guidelines</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
    <a class="sidebar-nav-item" href="/dldl.html">DLDL</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <style>
          .icon {
            width: 1em;
            height: 1em;
            vertical-align: -0.125em;
          }
        </style>
        <a href="mailto:redaktion@libreas.eu"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill = "#700000" d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48L48 64zM0 176L0 384c0 35.3 28.7 64 64 64l384 0c35.3 0 64-28.7 64-64l0-208L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg></a>
        <a href="https://github.com/libreas"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 448 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill = "#700000" d="M448 96c0-35.3-28.7-64-64-64H64C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96zM265.8 407.7c0-1.8 0-6 .1-11.6c.1-11.4 .1-28.8 .1-43.7c0-15.6-5.2-25.5-11.3-30.7c37-4.1 76-9.2 76-73.1c0-18.2-6.5-27.3-17.1-39c1.7-4.3 7.4-22-1.7-45c-13.9-4.3-45.7 17.9-45.7 17.9c-13.2-3.7-27.5-5.6-41.6-5.6s-28.4 1.9-41.6 5.6c0 0-31.8-22.2-45.7-17.9c-9.1 22.9-3.5 40.6-1.7 45c-10.6 11.7-15.6 20.8-15.6 39c0 63.6 37.3 69 74.3 73.1c-4.8 4.3-9.1 11.7-10.6 22.3c-9.5 4.3-33.8 11.7-48.3-13.9c-9.1-15.8-25.5-17.1-25.5-17.1c-16.2-.2-1.1 10.2-1.1 10.2c10.8 5 18.4 24.2 18.4 24.2c9.7 29.7 56.1 19.7 56.1 19.7c0 9 .1 21.7 .1 30.6c0 4.8 .1 8.6 .1 10c0 4.3-3 9.5-11.5 8C106 393.6 59.8 330.8 59.8 257.4c0-91.8 70.2-161.5 162-161.5s166.2 69.7 166.2 161.5c.1 73.4-44.7 136.3-110.7 158.3c-8.4 1.5-11.5-3.7-11.5-8zm-90.5-54.8c-.2-1.5 1.1-2.8 3-3.2c1.9-.2 3.7 .6 3.9 1.9c.3 1.3-1 2.6-3 3c-1.9 .4-3.7-.4-3.9-1.7zm-9.1 3.2c-2.2 .2-3.7-.9-3.7-2.4c0-1.3 1.5-2.4 3.5-2.4c1.9-.2 3.7 .9 3.7 2.4c0 1.3-1.5 2.4-3.5 2.4zm-14.3-2.2c-1.9-.4-3.2-1.9-2.8-3.2s2.4-1.9 4.1-1.5c2 .6 3.3 2.1 2.8 3.4c-.4 1.3-2.4 1.9-4.1 1.3zm-12.5-7.3c-1.5-1.3-1.9-3.2-.9-4.1c.9-1.1 2.8-.9 4.3 .6c1.3 1.3 1.8 3.3 .9 4.1c-.9 1.1-2.8 .9-4.3-.6zm-8.5-10c-1.1-1.5-1.1-3.2 0-3.9c1.1-.9 2.8-.2 3.7 1.3c1.1 1.5 1.1 3.3 0 4.1c-.9 .6-2.6 0-3.7-1.5zm-6.3-8.8c-1.1-1.3-1.3-2.8-.4-3.5c.9-.9 2.4-.4 3.5 .6c1.1 1.3 1.3 2.8 .4 3.5c-.9 .9-2.4 .4-3.5-.6zm-6-6.4c-1.3-.6-1.9-1.7-1.5-2.6c.4-.6 1.5-.9 2.8-.4c1.3 .7 1.9 1.8 1.5 2.6c-.4 .9-1.7 1.1-2.8 .4z"/></svg></a>
        <a href="https://www.instagram.com/libreas.libraryideas/"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 448 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill = "#700000" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg></a>
        <a href="https://openbiblio.social/@libreas"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 448 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill = "#700000" d="M433 179.1c0-97.2-63.7-125.7-63.7-125.7-62.5-28.7-228.6-28.4-290.5 0 0 0-63.7 28.5-63.7 125.7 0 115.7-6.6 259.4 105.6 289.1 40.5 10.7 75.3 13 103.3 11.4 50.8-2.8 79.3-18.1 79.3-18.1l-1.7-36.9s-36.3 11.4-77.1 10.1c-40.4-1.4-83-4.4-89.6-54a102.5 102.5 0 0 1 -.9-13.9c85.6 20.9 158.7 9.1 178.8 6.7 56.1-6.7 105-41.3 111.2-72.9 9.8-49.8 9-121.5 9-121.5zm-75.1 125.2h-46.6v-114.2c0-49.7-64-51.6-64 6.9v62.5h-46.3V197c0-58.5-64-56.6-64-6.9v114.2H90.2c0-122.1-5.2-147.9 18.4-175 25.9-28.9 79.8-30.8 103.8 6.1l11.6 19.5 11.6-19.5c24.1-37.1 78.1-34.8 103.8-6.1 23.7 27.3 18.4 53 18.4 175z"/></svg></i></a>
        <a href="https://edoc.hu-berlin.de/feed/atom_1.0/18452/149"><svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 448 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill = "#700000" d="M0 64C0 46.3 14.3 32 32 32c229.8 0 416 186.2 416 416c0 17.7-14.3 32-32 32s-32-14.3-32-32C384 253.6 226.4 96 32 96C14.3 96 0 81.7 0 64zM0 416a64 64 0 1 1 128 0A64 64 0 1 1 0 416zM32 160c159.1 0 288 128.9 288 288c0 17.7-14.3 32-32 32s-32-14.3-32-32c0-123.7-100.3-224-224-224c-17.7 0-32-14.3-32-32s14.3-32 32-32z"/></svg></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe31/inhalt/">LIBREAS. Library Ideas # 31</a></strong> <br><br>
</div>




    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe31/pankow/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="http://nbn-resolving.de/urn:nbn:de:kobv:11-110-18452/19668-6">Download PDF @ edoc HU Berlin</a>
            <br>
            urn:nbn:de:kobv:11-110-18452/19668-6 </small>
        </div>
        
    
    
        

        
        <h1 itemprop="name" class="title">Buch, Karow. Ein Ortstermin in zwei Berliner öffentlichen Bibliotheken</h1>
        
        

        <div class="titelei">
        
        <i itemprop="author">Ben Kaden</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Ben Kaden</i> 
            
            
            
        </div>
 -->



        

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Ben Kaden,
            
            
             
            "Buch, Karow. Ein Ortstermin in zwei Berliner öffentlichen Bibliotheken".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 31 (<span itemprop="datePublished">2017</span>). <a itemprop="url" href="https://libreas.eu/ausgabe31/pankow/meta.yaml">https://libreas.eu/ausgabe31/pankow/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2024-07-22</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
