
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>Spurensuche: Bibliothekarinnen, Berufsgeschichte, Sprache in Nachrufen. Ein Dialog - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">

	<!--
	<meta name="description" content="> > > LIBREAS. Library Ideas # 25 Download PDF @ edoc HU Berlin urn:nbn:de:kobv:11-100219329 Spurensuche: Bibliothekarinnen, Berufsgeschichte, &hellip;">
	 -->

<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="Spurensuche: Bibliothekarinnen, Berufsgeschichte, Sprache in Nachrufen. Ein Dialog" />
    
    
    
    <meta property="dc:creator" content="Heike Stadler" />
    
    <meta property="dc:creator" content="Karsten Schuldt" />
    
    
    
    <meta property="dc:date" content="2014" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="http://libreas.eu/ausgabe25/01editorial/meta.yaml" />
    
    <meta property="dc:rigths" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/3.0/" content="CC-BY 3.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content=""/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="25" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2014" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="http://libreas.eu/ausgabe25/01editorial/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
	<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-46475342-1', 'libreas.eu');
ga('send', 'pageview');

</script>
	
</head>




<body>
	<div class="container">
		<div class="left-col">
			<div class="intrude-less">
			<header id="header" class="inner"><h1  style="color:#FFFFFF"><a href="/">LIBREAS<br><small>Library Ideas</small></a></h1>



<nav id="main-nav"><ul>
	<li><a href="/ausgabe25/">Aktuelle Ausgabe</a></li>
	<li><a href="/archiv.htm">Archiv</a></li>
	<li><a href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a></li>
	<hr>
	<li><a href="/autorinnen">AutorInnen</a></li>
	<li><a href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a></li>
	<li><a href="/authorguides">Hinweise</a></li>
	<hr>
	<li><a href="http://libreas.wordpress.com/">Blog</a></li>
	<li><a href="http://libreas.tumblr.com/">Tumblr</a></li>
	<li><a href="http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a></li>
	<hr>
	<li><a href="http://libreas-verein.eu">Verein</a></li>
	<hr>
	<li><a href="/about">Impressum</a></li>
</ul>

</nav>
<nav id="sub-nav">
	<div class="social">
		
		<a class="facebook" href="http://www.facebook.com/libreas" title="Facebook">Facebook</a>
		
		
		
		<a class="twitter" href="http://twitter.com/libreas" title="Twitter">Twitter</a>
		
		
		<a class="github" href="https://github.com/libreas" title="GitHub">GitHub</a>
		
		
		
		
		
		
		
		
		<a class="rss" href="https://github.com/libreas.atom" title="RSS">RSS</a>
		
	</div>
</nav>

</header>				
			</div>
		</div>	
		<div class="mid-col">
			
				
			
			<div class="mid-col-container">
				<div id="content" class="inner">
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe25/00inhalt/">LIBREAS. Library Ideas # 25</a></strong> <br><br>
</div>




    
    <div align="right">
        <small><a itemprop="sameAs" href="http://nbn-resolving.de/urn:nbn:de:kobv:11-100219329">Download PDF @ edoc HU Berlin</a>
            <br>
            urn:nbn:de:kobv:11-100219329 </small>
        </div>
        

        
        <br>
        <h1 itemprop="name" class="title">Spurensuche: Bibliothekarinnen, Berufsgeschichte, Sprache in Nachrufen. Ein Dialog</h1>
        


        
        <div class="titelei">
            
            
            
            <i itemprop="author">Heike Stadler</i>
            
            
            
            <i>&amp;</i> <i itemprop="author">Karsten Schuldt</i>
            
            
        </div>
        



        

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Heike Stadler,
            
            
            
            Karsten Schuldt,
            
            "Spurensuche: Bibliothekarinnen, Berufsgeschichte, Sprache in Nachrufen. Ein Dialog". <i itemprop="provider">LIBREAS. Library Ideas</i>, 25 (<span itemprop="datePublished">2014</span>). <a itemprop="url" href="http://libreas.eu/ausgabe25/01editorial/meta.yaml">http://libreas.eu/ausgabe25/01editorial/meta.yaml</a>
        </small>
        <hr>
    </p>
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>

<div class="share">
	<div class="addthis_toolbox addthis_default_style ">
	
	
	<a class="addthis_button_tweet"></a>
	
	
	<a class="addthis_counter addthis_pill_style"></a>
	</div>
  <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid="></script>
</div>




</div>
			</div>
			<footer id="footer" class="inner"><hr>
<p>
Herausgegeben am <a href="http://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="http://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a>.<p>

ISSN: 1860-7950

Kontakt: <a href="mailto:redaktion@libreas.eu">redaktion@libreas.eu</a>
</p>

<br>

<p><a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported (CC BY 3.0)</a>, if not stated otherwise</p>
2014

    LIBREAS. Library Ideas

<br>
Powered by Octopress.


Design credit: <a href="http://shashankmehta.in/archive/2012/greyshade.html">Shashank Mehta</a></footer>
			<script src="/javascripts/slash.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>







		</div>
	</div>
</body>
</html>
