
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>The Sound of Gesprochene Wikisource - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="The Sound of Gesprochene Wikisource" />
    
    
    
    <meta property="dc:creator" content="Jens Bemme" />
    
    <meta property="dc:creator" content="Caroline Förster" />
    
    <meta property="dc:creator" content="Juliane Flade" />
    
    
    
    <meta property="dc:date" content="2024" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe45/bemme/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content="Digitale Sammlungen klingen erstmal nicht. Aber dann. ‘Spoken Wikisource – German’ enthält Töne von Joachim Ringelnatz, gesprochene, Texte aus ‘Die Gartenlaube’, auch ‘spoken’, Stimmen und Ideen. Der Klang der ‘Gesprochenen Wikisource’ ist vielschichtig beziehungsweise kann und könnte er sehr vielseitig sein – metaphorisch als der Klang des Projekts ‘Gesprochene Wikisource’, durch die Stimmen der beteiligten Gemeinschaften oder der Räume, in denen diese Aufnahmen entstehen; zum Beispiel Tonstudios, in denen Sprecher:innen sprechen. Gesprochen werden Textquellen aus Wikisource akustisch erfahrbar. Wahrnehmbar wird dadurch nicht nur der Inhalt, sondern auch eine Textinterpretation. Im Bibliothekskatalog gibt es diese Möglichkeit noch nicht, die Quellen sind entweder als Text oder Audio verfügbar, hybrid selten. Beim Einsprechen und Hören ist ein Teil der Rezeption zu spüren: Wie verstehe und interpretiere ich den Text einer Vorleser- oder Sprecherin, die sich mit gesprochenem Volltext des Portals Wikisource auseinandersetzt?! Dabei findet Interpretation statt, mehr als eine. Wikisource gewinnt so als gesprochene digitale Sammlung weitere Deutungs- und Metaebenen – Nuancen, Zugänge und Freiheitsgrade, Bedeutungen, Links. Dieser ‘Sound of Gesprochene Wikisource’ ist ein Nachhall medialer Auseinandersetzungen mit … Text in einer Bibliothek. Die Autorinnen berichten, betonen und spielen dabei mit Aspekten der ‘Gesprochenen Wikisource’ in historischen, bibliophilen und modernen Linkzusammenhängen mit dem Podcaststudio der SLUB, mit den offenen Kulturdaten des Dresdner Geschichtsvereins, mit &#39;DatenlaubeJam&#39; am Dienstag und Lesungen im Advent – ‘The Sound of Wikisource’ sozusagen, ‘read, spoken and linked open’."/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="45" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2024" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe45/bemme/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe44/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">Autor*innen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Author guidelines</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
    <a class="sidebar-nav-item" href="/dldl.html">DLDL</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <a href="mailto:redaktion@libreas.eu"><i class="fa fa-envelope"></i></a>
        <a href="https://github.com/libreas"><i class="fa fa-github-square"></i></a>
        <a href="https://www.instagram.com/libreas.libraryideas/"><i class="fa fa-instagram"></i></a>
        <a href="https://twitter.com/libreas"><i class="fa fa-twitter"></i></a>
        <a href="https://edoc.hu-berlin.de/feed/atom_1.0/18452/149"><i class="fa fa-rss"></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe45/inhalt/">LIBREAS. Library Ideas # 45</a></strong> <br><br>
</div>





    
        
    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe45/bemme/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="main.pdf">Download PDF</a></small>
        </div>
    
    
        

        
        <h1 itemprop="name" class="title">The Sound of Gesprochene Wikisource</h1>
        
        

        <div class="titelei">
        
        <i itemprop="author">Jens Bemme, Caroline Förster, Juliane Flade</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Jens Bemme</i> 
            
            
              
            <i itemprop="author">Caroline Förster</i>
            
            
               
            </i><i itemprop="author">Juliane Flade</i>
            
            
            
        </div>
 -->



        

        <p><small itemprop="description">Digitale Sammlungen klingen erstmal nicht. Aber dann. ‘Spoken Wikisource – German’ enthält Töne von Joachim Ringelnatz, gesprochene, Texte aus ‘Die Gartenlaube’, auch ‘spoken’, Stimmen und Ideen. Der Klang der ‘Gesprochenen Wikisource’ ist vielschichtig beziehungsweise kann und könnte er sehr vielseitig sein – metaphorisch als der Klang des Projekts ‘Gesprochene Wikisource’, durch die Stimmen der beteiligten Gemeinschaften oder der Räume, in denen diese Aufnahmen entstehen; zum Beispiel Tonstudios, in denen Sprecher:innen sprechen. Gesprochen werden Textquellen aus Wikisource akustisch erfahrbar. Wahrnehmbar wird dadurch nicht nur der Inhalt, sondern auch eine Textinterpretation. Im Bibliothekskatalog gibt es diese Möglichkeit noch nicht, die Quellen sind entweder als Text oder Audio verfügbar, hybrid selten. Beim Einsprechen und Hören ist ein Teil der Rezeption zu spüren: Wie verstehe und interpretiere ich den Text einer Vorleser- oder Sprecherin, die sich mit gesprochenem Volltext des Portals Wikisource auseinandersetzt?! Dabei findet Interpretation statt, mehr als eine. Wikisource gewinnt so als gesprochene digitale Sammlung weitere Deutungs- und Metaebenen – Nuancen, Zugänge und Freiheitsgrade, Bedeutungen, Links. Dieser ‘Sound of Gesprochene Wikisource’ ist ein Nachhall medialer Auseinandersetzungen mit … Text in einer Bibliothek. Die Autorinnen berichten, betonen und spielen dabei mit Aspekten der ‘Gesprochenen Wikisource’ in historischen, bibliophilen und modernen Linkzusammenhängen mit dem Podcaststudio der SLUB, mit den offenen Kulturdaten des Dresdner Geschichtsvereins, mit 'DatenlaubeJam' am Dienstag und Lesungen im Advent – ‘The Sound of Wikisource’ sozusagen, ‘read, spoken and linked open’.</small></p>

        

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Jens Bemme,
            
            
            
            Caroline Förster,
            
            
            
            Juliane Flade,
            
            
             
            "The Sound of Gesprochene Wikisource".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 45 (<span itemprop="datePublished">2024</span>). <a itemprop="url" href="https://libreas.eu/ausgabe45/bemme/meta.yaml">https://libreas.eu/ausgabe45/bemme/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2024-07-19</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
