
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>Personenbezogene Forschungsdaten in unverdächtigen Disziplinen: Das Beispiel der Erd-, Umwelt- und Agrarwissenschaften - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="Personenbezogene Forschungsdaten in unverdächtigen Disziplinen: Das Beispiel der Erd-, Umwelt- und Agrarwissenschaften" />
    
    
    
    <meta property="dc:creator" resource="http://orcid.org/0000-0002-7328-3625" content="Niklas K. Hartmann" />
    
    
    
    <meta property="dc:date" content="2019" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe36/hartmann/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content="Am Beispiel der Erd- und Umweltwissenschaften (einschließlich der landschafts- und standortbezogenen Teilgebiete der Agrarwissenschaften) zeigt dieser Beitrag, dass auch in scheinbar „unverdächtigen“ Disziplinen personenbezogene Forschungsdaten vorkommen. Eine Auswertung der Literatur zeigt, dass allgemeine Handreichungen zum Datenschutz in der Forschung kaum Unterstützung bei der Arbeit mit den für diese Disziplinen besonders relevanten Fällen bieten. Für die in den Erd- und Umweltwissenschaften besonders relevanten raumbezogenen Daten kommt hinzu, dass selbst unter Fachjuristinnen Uneinigkeit über die datenschutzrechtliche Bewertung herrscht. Die Ergebnisse einer empirischen Vorstudie zeigen eine ganze Reihe verschiedener Arten personenbezogener Forschungsdaten auf, die in der Forschungspraxis der Erd- und Umweltwissenschaften eine Rolle spielen. Sie legen außerdem nahe, dass der Umgang mit personenbezogenen Daten in der Forschungspraxis der Erd- und Umweltwissenschaften auf Grund der mangelnden Vertrautheit mit dem Datenschutz nicht immer den rechtlichen Anforderungen entspricht. Auch Unterstützung durch Fachgesellschaften und Infrastruktureinrichtungen – etwa in Form disziplinspezifischer Handreichungen, qualifizierter Beratung oder institutionalisierten Möglichkeiten, Daten sicher zu archivieren und gegebenenfalls      zugangsbeschränkt zu publizieren – bestehen kaum. Aus dieser Situation ergeben sich Herausforderungen an die Weiterentwicklung der disziplinären Datenkultur und Dateninfrastruktur, beispielsweise im Rahmen des Prozesses zum Aufbau einer Nationalen Forschungsdateninfrastruktur (NFDI). Zu den Möglichkeiten für Infrastruktureinrichtungen, diese Weiterentwicklung zu unterstützen, zeigt dieser Beitrag Handlungsoptionen auf."/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="36" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2019" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe36/hartmann/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe36/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">AutorInnen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Hinweise</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <a href="mailto:redaktion@libreas.eu"><i class="fa fa-envelope"></i></a>
        <a href="https://github.com/libreas"><i class="fa fa-github-square"></i></a>
        <a href="https://www.facebook.com/libreas"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/libreas"><i class="fa fa-twitter"></i></a>
        <a href="https://github.com/libreas.atom"><i class="fa fa-rss"></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe36/inhalt/">LIBREAS. Library Ideas # 36</a></strong> <br><br>
</div>




    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe36/hartmann/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="http://nbn-resolving.de/urn:nbn:de:kobv:11-110-18452/22150-5">Download PDF @ edoc HU Berlin</a>
            <br>
            urn:nbn:de:kobv:11-110-18452/22150-5 </small>
        </div>
        
    
    
        

        
        <h1 itemprop="name" class="title">Personenbezogene Forschungsdaten in unverdächtigen Disziplinen: Das Beispiel der Erd-, Umwelt- und Agrarwissenschaften</h1>
        
        

        <div class="titelei">
        
        <i itemprop="author">Niklas K. Hartmann</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Niklas K. Hartmann</i> 
            
            
            
        </div>
 -->



        

        <p><small itemprop="description">Am Beispiel der Erd- und Umweltwissenschaften (einschließlich der landschafts- und standortbezogenen Teilgebiete der Agrarwissenschaften) zeigt dieser Beitrag, dass auch in scheinbar „unverdächtigen“ Disziplinen personenbezogene Forschungsdaten vorkommen. Eine Auswertung der Literatur zeigt, dass allgemeine Handreichungen zum Datenschutz in der Forschung kaum Unterstützung bei der Arbeit mit den für diese Disziplinen besonders relevanten Fällen bieten. Für die in den Erd- und Umweltwissenschaften besonders relevanten raumbezogenen Daten kommt hinzu, dass selbst unter Fachjuristinnen Uneinigkeit über die datenschutzrechtliche Bewertung herrscht. Die Ergebnisse einer empirischen Vorstudie zeigen eine ganze Reihe verschiedener Arten personenbezogener Forschungsdaten auf, die in der Forschungspraxis der Erd- und Umweltwissenschaften eine Rolle spielen. Sie legen außerdem nahe, dass der Umgang mit personenbezogenen Daten in der Forschungspraxis der Erd- und Umweltwissenschaften auf Grund der mangelnden Vertrautheit mit dem Datenschutz nicht immer den rechtlichen Anforderungen entspricht. Auch Unterstützung durch Fachgesellschaften und Infrastruktureinrichtungen – etwa in Form disziplinspezifischer Handreichungen, qualifizierter Beratung oder institutionalisierten Möglichkeiten, Daten sicher zu archivieren und gegebenenfalls      zugangsbeschränkt zu publizieren – bestehen kaum. Aus dieser Situation ergeben sich Herausforderungen an die Weiterentwicklung der disziplinären Datenkultur und Dateninfrastruktur, beispielsweise im Rahmen des Prozesses zum Aufbau einer Nationalen Forschungsdateninfrastruktur (NFDI). Zu den Möglichkeiten für Infrastruktureinrichtungen, diese Weiterentwicklung zu unterstützen, zeigt dieser Beitrag Handlungsoptionen auf.</small></p>

        

        

        <br>

        <p><small itemprop="description">English-language abstract: Using the example of the earth and environmental sciences (including the branches of the agricultural sciences engaged in landscape- and plot-based research) this article shows how research data containing personal data can feature prominently even in disciplines usually assumed to be “unsuspicious”. A review of the literature shows that general recommendations on data protection in research offer little support regarding the kinds of data that are of particular relevance for these disciplines. In the case of spatial data, even specialised jurists disagree about the extent to which data protection law is applicable. Results of a pilot survey demonstrate a whole range of personal data that occur in the research practice of the earth and environmental sciences with at least some regularity. These results also suggest that, due to unfamiliarity with data protection, the handling of personal data during research does not always comply with regulatory requirements. Moreover, there is very little support by scholarly associations or infrastructure facilities in terms of e.g. discipline-specific recommendations, consultation services, or possibilities to institutionally archive personal data and possibly give restricted access for reuse. This situation presents a challenge to the development of disciplinary data culture and data infrastructures which the process to set up a National Research Data Infrastructure (NFDI) in Germany may be able to address. This article highlights possible courses of action for infrastructure facilities to support these developments.</small></p>

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Niklas K. Hartmann,
            
            
             
            "Personenbezogene Forschungsdaten in unverdächtigen Disziplinen: Das Beispiel der Erd-, Umwelt- und Agrarwissenschaften".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 36 (<span itemprop="datePublished">2019</span>). <a itemprop="url" href="https://libreas.eu/ausgabe36/hartmann/meta.yaml">https://libreas.eu/ausgabe36/hartmann/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 Unported (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2020-06-30</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
