
<!DOCTYPE HTML>

<html lang="en">

<head>
	<meta charset="utf-8">
	<title>The Library’s Contribution to University Scientific Journal Publishing and Promotion: Practical Review - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="The Library’s Contribution to University Scientific Journal Publishing and Promotion: Practical Review" />
    
    
    
    <meta property="dc:creator" content="Yurii Horban" />
    
    <meta property="dc:creator" content="Viacheslav Lukianenko" />
    
    <meta property="dc:creator" content="Olena Skachenko" />
    
    
    
    <meta property="dc:date" content="2020" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe38/horban/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content="The article describes the library’s contribution to editorial and publishing support and promotion of thirteen new scientific journals, published by the Kyiv National University of Culture and Arts (Ukraine). The article provides an analysis of the mission, objectives, and editorial staff of scientific publications as well as the journals’ status and stage of indexing in the international lists and databases.
In order to establish the journals, at a first stage, the Ukrainian arts and culture scientific journals market has been monitored. At a second stage the Scientific Library turned into an active participant of the publishing process and the editorial support for thirteen scientific publications. At a third stage all journal content is included in international indexing systems.
The insights into the new scientific journal publishing process, experienced by the University, can be extremely beneficial to other libraries. The authors offer their vision of the prospects for the development of journals and a list of activities to achieve their goals.
The activities of the scientific library in the future are seen in the development of information-analytical monitoring and bibliometric analysis of the university’s communications system; development of an algorithm for presenting the profiles of scientists in search engines and international abstract databases; promoting the inclusion of university scientific journals in the international Scopus and Web of Science databases."/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="38" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2020" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe38/horban/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe39/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">AutorInnen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Hinweise</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <a href="mailto:redaktion@libreas.eu"><i class="fa fa-envelope"></i></a>
        <a href="https://github.com/libreas"><i class="fa fa-github-square"></i></a>
        <a href="https://www.facebook.com/libreas"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/libreas"><i class="fa fa-twitter"></i></a>
        <a href="https://github.com/libreas.atom"><i class="fa fa-rss"></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe38/inhalt/">LIBREAS. Library Ideas # 38</a></strong> <br><br>
</div>




    
        
    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe38/horban/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="master.pdf">Download PDF</a></small>
        </div>
    
    
        

        
        <h1 itemprop="name" class="title">The Library’s Contribution to University Scientific Journal Publishing and Promotion: Practical Review</h1>
        
        

        <div class="titelei">
        
        <i itemprop="author">Yurii Horban, Viacheslav Lukianenko, Olena Skachenko</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Yurii Horban</i> 
            
            
              
            <i itemprop="author">Viacheslav Lukianenko</i>
            
            
               
            </i><i itemprop="author">Olena Skachenko</i>
            
            
            
        </div>
 -->



        

        <p><small itemprop="description">The article describes the library’s contribution to editorial and publishing support and promotion of thirteen new scientific journals, published by the Kyiv National University of Culture and Arts (Ukraine). The article provides an analysis of the mission, objectives, and editorial staff of scientific publications as well as the journals’ status and stage of indexing in the international lists and databases.
In order to establish the journals, at a first stage, the Ukrainian arts and culture scientific journals market has been monitored. At a second stage the Scientific Library turned into an active participant of the publishing process and the editorial support for thirteen scientific publications. At a third stage all journal content is included in international indexing systems.
The insights into the new scientific journal publishing process, experienced by the University, can be extremely beneficial to other libraries. The authors offer their vision of the prospects for the development of journals and a list of activities to achieve their goals.
The activities of the scientific library in the future are seen in the development of information-analytical monitoring and bibliometric analysis of the university’s communications system; development of an algorithm for presenting the profiles of scientists in search engines and international abstract databases; promoting the inclusion of university scientific journals in the international Scopus and Web of Science databases.</small></p>

        

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Yurii Horban,
            
            
            
            Viacheslav Lukianenko,
            
            
            
            Olena Skachenko,
            
            
             
            "The Library’s Contribution to University Scientific Journal Publishing and Promotion: Practical Review".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 38 (<span itemprop="datePublished">2020</span>). <a itemprop="url" href="https://libreas.eu/ausgabe38/horban/meta.yaml">https://libreas.eu/ausgabe38/horban/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2021-10-13</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
