
<!DOCTYPE HTML>

<html lang="de">

<head>
	<meta charset="utf-8">
	<title>Überlegungen zu einer nachhaltigen Forschungsdateninfrastruktur - LIBREAS. Library Ideas</title>
	<meta name="author" content="LIBREAS. Library Ideas">


<!-- RDFa DC -->

 <!-- RDFa Metadata (in DublinCore) -->
    
    <meta property="dc:title" content="Überlegungen zu einer nachhaltigen Forschungsdateninfrastruktur" />
    
    
    
    <meta property="dc:creator" content="Bernd Kulawik" />
    
    
    
    <meta property="dc:date" content="2019" />
    
    <meta property="dc:format" content="text/html" />
    <meta property="dc:language" content="de" />
    <meta property="dc:identifier" content="https://libreas.eu/ausgabe36/kulawik/meta.yaml" />
    
    <meta property="dc:rights" prefix="cc: http://creativecommons.org/ns#" rel="cc:license" href="https://creativecommons.org/licenses/by/4.0/" content="CC-BY 4.0" />
	
    <meta property="dc:source" content="LIBREAS. Library Ideas" />
    <meta property="dc:subject" content="Library and Information Science" />
    <meta property="dc:type" content="website" />
    <meta property="dc:description" content="In diesem Essay wird eine radikale Lösung des Problems wirklich langfristiger Datensicherung und -verfügbarkeit vorgeschlagen. Sie beruht auf der zuvor erläuterten Einschätzung, dass die Vielfalt und Komplexität heutiger IT-Systeme weder mit vertretbarem Aufwand für die Zukunft konserviert werden kann, noch in der Zukunft rekonstruierbar sein wird. Ein Ausweg könnte die Schaffung einer (internationalen) Institution mit &lt;q&gt;Ewigkeitsgarantie&lt;/q&gt; sein, welche die Entwicklung und Betreuung einer freien Hard- und Softwareplattform übernimmt, mit der insbesondere Forschungsprojekte und -einrichtungen, aber auch Firmen oder Privatpersonen arbeiten können, die ihre Daten abschließend der Institution zur dauerhaften Speicherung übergeben wollen. Bei der Entwicklung dieser Plattform könnten vorausweisende Lösungen aus der bisherigen IT-Enwicklung übernommen; bekannte, aber aus Kompatibilitätsgründen nicht behobene Fehler und Irrtümer jedoch vermieden werden. Außerdem könnte das System zugleich als eine wirklich offene Plattform für Repositorien zur Veröffentlichung von Daten und Ergebnissen im Open Access bilden und undurchsichtige Verfahren beispielsweise im Peer Review und der Messung von Forschungsrelevanz ablösen. Da Bibliotheken, Archive und Museen diejenigen Institutionen sind, die über umfangreichste historisch gewachsene Erfahrungen in der Speicherung und Erschließung von Daten im weitesten Sinne haben, sollten sie bei Konzeption und Betrieb dieser Institution eine führende Rolle spielen."/>
    <meta property="dc:source" resource="urn:ISSN:1860-7950" /> 

<!-- Google Scholar -->

	<meta name="citation_journal_title" content="LIBREAS. Library Ideas" />
	<meta name="citation_issue" content="36" />
	<meta name="citation_issn" content="1860-7950" />
	
    <meta name="citation_publication_date" content="2019" />
    


  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="/atom.xml" rel="alternate" title="LIBREAS. Library Ideas" type="application/atom+xml">
	
	<link rel="canonical" href="https://libreas.eu/ausgabe36/kulawik/meta.yaml">
	<link href="/favicon.png" rel="shortcut icon">
	<link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">


    <!--   
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="favicon.png"> -->
  
	
</head>




  <body class="theme-base-wes">

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">
    <a href="/">LIBREAS. Library Ideas</a>
  </div>

  <nav class="sidebar-nav">

    	<a class="sidebar-nav-item" href="/ausgabe41/">Aktuelle Ausgabe</a>
	<a class="sidebar-nav-item" href="/archiv.htm">Archiv</a>
	<a class="sidebar-nav-item" href="http://edoc.hu-berlin.de/browsing/libreas/">edoc pdf-Archiv</a>
	<a class="sidebar-nav-item" href="/autorinnen">Autor*innen</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/category/libreas-call-for-papers/">Call for Papers</a>
	<a class="sidebar-nav-item" href="/authorguides">Author guidelines</a>
	<a class="sidebar-nav-item" href="http://libreas.wordpress.com/">Blog</a>
	<a class="sidebar-nav-item" href="http://libreas.tumblr.com/">Tumblr</a>
    <a class="sidebar-nav-item" href="https://www.zotero.org/groups/4620604/">Zotero DLDL</a>
	<a class="sidebar-nav-item" href="https://web.archive.org/web/20171112100417/http://www.ib.hu-berlin.de/~libreas/libreas_neu/podcasts/">Podcasts</a>
	<a class="sidebar-nav-item" href="http://libreas-verein.eu">Verein</a>
	<a class="sidebar-nav-item" href="/about">Impressum</a>

  </nav>
</div>


    <!-- Wrap is the content to shift when toggling the sidebar. We wrap the
         content to avoid any CSS collisions with our real content. -->
    <!-- <div class="wrap">
       <div class="masthead">
        <div class="container">
          <h1 class="masthead-title">
            <a href="/" title="Home">LIBREAS. Library Ideas</a>
            <small><br></small>
          </h1>
        </div>
      </div> -->


      <div class="container content">
      <!-- GitHub et al icon -->
      <div align="right" class="icons">
        <a href="mailto:redaktion@libreas.eu"><i class="fa fa-envelope"></i></a>
        <a href="https://github.com/libreas"><i class="fa fa-github-square"></i></a>
        <a href="https://www.instagram.com/libreas.libraryideas/"><i class="fa fa-instagram"></i></a>
        <a href="https://twitter.com/libreas"><i class="fa fa-twitter"></i></a>
        <a href="https://github.com/libreas.atom"><i class="fa fa-rss"></i></a>
</div>
        
<article class="page" itemscope itemtype="http://schema.org/ScholarlyArticle">

<div align="right">

<strong> > > > <a href="/ausgabe36/inhalt/">LIBREAS. Library Ideas # 36</a></strong> <br><br>
</div>




    
    <div align="right">
    <p><small><a itemprop="sameAs" href="https://via.hypothes.is/https://libreas.eu/ausgabe36/kulawik/meta.yaml">Annotate via hypothes.is</a></small></p>
        <small><a itemprop="sameAs" href="http://nbn-resolving.de/urn:nbn:de:kobv:11-110-18452/22144-3">Download PDF @ edoc HU Berlin</a>
            <br>
            urn:nbn:de:kobv:11-110-18452/22144-3 </small>
        </div>
        
    
    
        

        
        <h1 itemprop="name" class="title">Überlegungen zu einer nachhaltigen Forschungsdateninfrastruktur</h1>
        
        

        <div class="titelei">
        
        <i itemprop="author">Bernd Kulawik</i>
        
    </div>

<!-- 

        
        <div class="titelei">
            
              
              
            <i itemprop="author">Bernd Kulawik</i> 
            
            
            
        </div>
 -->



        

        <p><small itemprop="description">In diesem Essay wird eine radikale Lösung des Problems wirklich langfristiger Datensicherung und -verfügbarkeit vorgeschlagen. Sie beruht auf der zuvor erläuterten Einschätzung, dass die Vielfalt und Komplexität heutiger IT-Systeme weder mit vertretbarem Aufwand für die Zukunft konserviert werden kann, noch in der Zukunft rekonstruierbar sein wird. Ein Ausweg könnte die Schaffung einer (internationalen) Institution mit <q>Ewigkeitsgarantie</q> sein, welche die Entwicklung und Betreuung einer freien Hard- und Softwareplattform übernimmt, mit der insbesondere Forschungsprojekte und -einrichtungen, aber auch Firmen oder Privatpersonen arbeiten können, die ihre Daten abschließend der Institution zur dauerhaften Speicherung übergeben wollen. Bei der Entwicklung dieser Plattform könnten vorausweisende Lösungen aus der bisherigen IT-Enwicklung übernommen; bekannte, aber aus Kompatibilitätsgründen nicht behobene Fehler und Irrtümer jedoch vermieden werden. Außerdem könnte das System zugleich als eine wirklich offene Plattform für Repositorien zur Veröffentlichung von Daten und Ergebnissen im Open Access bilden und undurchsichtige Verfahren beispielsweise im Peer Review und der Messung von Forschungsrelevanz ablösen. Da Bibliotheken, Archive und Museen diejenigen Institutionen sind, die über umfangreichste historisch gewachsene Erfahrungen in der Speicherung und Erschließung von Daten im weitesten Sinne haben, sollten sie bei Konzeption und Betrieb dieser Institution eine führende Rolle spielen.</small></p>

        

        



        
        <p>
          <small>
            <br>
            Zitiervorschlag
            <br>
            
            
            Bernd Kulawik,
            
            
             
            "Überlegungen zu einer nachhaltigen Forschungsdateninfrastruktur".
            
            <i itemprop="provider">LIBREAS. Library Ideas</i>, 36 (<span itemprop="datePublished">2019</span>). <a itemprop="url" href="https://libreas.eu/ausgabe36/kulawik/meta.yaml">https://libreas.eu/ausgabe36/kulawik/meta.yaml</a>
        </small>
        <hr>
    </p>
   
    





    <div class="entry-content" itemprop="articleBody"></div>

    

</article>




        <footer class="footer">
<hr>
<p><a href="https://creativecommons.org/licenses/by/4.0/">All content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)</a>, if not otherwise stated.
</p>
<p>LIBREAS. Library Ideas wird herausgegeben am <a href="https://www.ibi.hu-berlin.de/">Institut für Bibliotheks- und Informationswissenschaft</a> der <a href="https://www.hu-berlin.de/">Humboldt-Universität zu Berlin</a></p>
<p>Hosted on <a href="http://github.com/libreas/libreas.github.io">GitHub</a>, made with <a href="http://octopress.org/">Jekyll/Octopress</a> and <a href="http://johnmacfarlane.net/pandoc/">pandoc</a></p>

<p>ISSN: 1860-7950</p>


    LIBREAS. Library Ideas

(last updated: <a href="https://github.com/libreas/libreas.github.io/commits/master">2022-06-14</a>)</p>

</footer>
      </div>
    </div>
<label for="sidebar-checkbox" class="sidebar-toggle"></label>

    <script>
      (function(document) {
        var toggle = document.querySelector('.sidebar-toggle');
        var sidebar = document.querySelector('#sidebar');
        var checkbox = document.querySelector('#sidebar-checkbox');

        document.addEventListener('click', function(e) {
          var target = e.target;

          if(!checkbox.checked ||
             sidebar.contains(target) ||
             (target === checkbox || target === toggle)) return;

          checkbox.checked = false;
        }, false);
      })(document);
    </script>
  </body>
</html>
